default: &default
  adapter: postgresql
  encoding: unicode
  username: rails
  password: rails
  host: localhost

development:
  <<: *default
  database: charts_development

test:
  <<: *default
  database: charts_test
